# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d4e193e791ec43a7411a84bc6524d0dc5e6b260c8318ac4bc60ba881e151c9be6d0ad54b987183aae76ba053ec20139403b7480f644dca2953ad72845992a7

test:
  secret_key_base: fcacb62a1fd7fa4354b1ee36018e3c0c166e45a3d42342a215efc7d40fc87e6face50462da114cd79c23f915f916bc5c878d5763406a97e25279952abdec0f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
